import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { ViewTransitions } from "next-view-transitions";
import { Suspense } from "react";
import { QueryProvider } from "@/components/providers/QueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Task manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ViewTransitions>
    <html lang="en">
      <body className={`${inter.className} dark:bg-[#1f1f1f]`}>
      <QueryProvider>
        <Suspense fallback={<div>Loading...</div>}>
          <ThemeProvider
              attribute = "class"
              defaultTheme = "system"
              enableSystem
              disableTransitionOnChange
              storageKey = "jotion-theme-2"
          >
            {children}
          </ThemeProvider>
        </Suspense>
      </QueryProvider>
      </body>
    </html>
    </ViewTransitions>
  );
}
